# Generated by Django 4.2.20 on 2025-07-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.PositiveIntegerField(unique=True, verbose_name='ID в Bitrix24')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('error', 'Ошибка')], max_length=10, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=50, verbose_name='Модель')),
                ('bitrix_id', models.PositiveIntegerField(null=True, verbose_name='ID в Bitrix24')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешно')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.PositiveIntegerField(unique=True, verbose_name='ID в Bitrix24')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('pending', 'На проверке'), ('completed', 'Завершена'), ('deleted', 'Удалена')], default='new', max_length=20, verbose_name='Статус')),
                ('original_time_estimate', models.FloatField(default=0, verbose_name='Время выполнения (часы)')),
                ('is_subtask', models.BooleanField(default=False, verbose_name='Это подзадача')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='tasks.employee', verbose_name='Создатель')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Родительская задача')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('new_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_reassignments', to='tasks.employee', verbose_name='Новый исполнитель')),
                ('old_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_reassignments', to='tasks.employee', verbose_name='Предыдущий исполнитель')),
                ('reassigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_reassignments', to='tasks.employee', verbose_name='Кто переназначил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Переназначение задачи',
                'verbose_name_plural': 'Переназначения задач',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['bitrix_id'], name='tasks_task_bitrix__0f36ec_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent_task'], name='tasks_task_parent__a05e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_subtask'], name='tasks_task_is_subt_675d1b_idx'),
        ),
    ]
