# Generated by Django 4.2.20 on 2025-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_creator_alter_task_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фото профиля'),
        ),
    ]
