# Generated by Django 4.2.20 on 2025-07-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_employee_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bitrix_id',
            field=models.PositiveIntegerField(verbose_name='ID в Bitrix24'),
        ),
    ]
