# Generated by Django 4.2.20 on 2025-07-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_bitrix_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bitrix_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID в Bitrix24'),
        ),
    ]
