# Generated by Django 4.2.20 on 2025-07-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_bitrix_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Времени затрачено (сек)'),
        ),
    ]
