# Generated by Django 4.2.20 on 2025-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bitrix_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на задачу в bitrix'),
        ),
        migrations.AlterField(
            model_name='task',
            name='original_time_estimate',
            field=models.FloatField(default=0, verbose_name='Время выполнения (секунды)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('pending', 'На паузе'), ('completed', 'Завершена'), ('deleted', 'Удалена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(verbose_name='Времени затрачено (сек)'),
        ),
    ]
