# Generated by Django 4.2.20 on 2025-07-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_bitrix_link_alter_task_original_time_estimate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_bitrix__0f36ec_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='bitrix_id',
        ),
    ]
