# Generated by Django 4.2.20 on 2025-07-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_tasks_task_bitrix__0f36ec_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_parent__a05e1a_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
    ]
