# Generated by Django 4.2.20 on 2025-07-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_task_tasks_task_parent__a05e1a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_is_subt_675d1b_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_subtask',
        ),
    ]
