# Generated by Django 4.2.20 on 2025-07-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_task_tasks_task_is_subt_675d1b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bitrix_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID в Bitrix24'),
        ),
    ]
