# Generated by Django 4.2.20 on 2025-07-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_bitrix_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bitrix_link',
        ),
    ]
