# Generated by Django 4.2.20 on 2025-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_task_bitrix_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Пароль'),
        ),
    ]
