# Generated by Django 4.2.20 on 2025-07-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_employee_user_alter_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='task',
            name='accumulated_time',
            field=models.IntegerField(default=0, verbose_name='Накопленное время (сек)'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_timer_running',
            field=models.BooleanField(default=False, verbose_name='Таймер запущен'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск таймера'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя сотрудника'),
        ),
    ]
