# Generated by Django 4.2.20 on 2025-08-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_employee_user_remove_task_time_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('pending', 'На паузе'), ('completed', 'Завершена'), ('deleted', 'Удалена'), ('deleted', 'Отложена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
