# Generated by Django 4.2.20 on 2025-08-09 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0019_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bitrix_id',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID в Bitrix24'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='icon',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, editable=False, help_text='Используется один раз для установки пароля User и затем очищается.', max_length=30, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('error', 'Ошибка')], db_index=True, max_length=10, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='bitrix_id',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='ID в Bitrix24'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='task',
            name='accumulated_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Накопленное время (сек)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='bitrix_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID в Bitrix24'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='original_time_estimate',
            field=models.PositiveIntegerField(default=0, verbose_name='План (секунды)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('pending', 'На паузе'), ('completed', 'Завершена'), ('deleted', 'Удалена'), ('deferred', 'Отложена')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['model_name', 'bitrix_id'], name='tasks_syncl_model_n_c004c7_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['timestamp'], name='tasks_syncl_timesta_db5d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['bitrix_id'], name='tasks_task_bitrix__0f36ec_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['employee', 'status'], name='tasks_task_employe_e8653c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='tasks_task_deadlin_736196_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='tasks_task_created_5da2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreassignment',
            index=models.Index(fields=['task', 'timestamp'], name='tasks_taskr_task_id_218d3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('bitrix_id__isnull', False)), fields=('bitrix_id',), name='uniq_task_bitrix_id_not_null'),
        ),
    ]
