# Generated by Django 4.2.20 on 2025-08-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_employee_password_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='uniq_task_bitrix_id_not_null',
        ),
    ]
